coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%

ignore:
  - "tests/"
  - "scripts/"
  - "venv/"
  - "build/"
  - "**/__pycache__/"
  - "*.dsp"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false